name: Build Project

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Node ${{ matrix.node }} build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install pam libs
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make build-essential libpam0g-dev

      - name: Install dummy deps to avoid problems with carta-frontend's patch-package uses
        run: npm install golden-layout react-split-pane --no-save --ignore-scripts

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run prepare